Product editing #2
h-hashimoto1212/freemarket_sample_66a pull request #61
Opened 2020-01-22 11:28 UTC by yugo333

# What
edit selecter編集しました

#why
editページで編集する際投稿時に選択した値を表示させる為

2020-01-22 12:01 UTC, oono0908 commented
LGTM

2020-01-22 12:18 UTC, h-hashimoto1212 requested changes
修正お願いします。

2020-01-22 12:18 UTC, h-hashimoto1212 commented on app/views/products/edit.html.haml
> +                  = form.select :condition, options_for_select(Product.conditions.map{|c|c} , @product.condition_before_type_cast), {}, {class: "exhibition_main__container__product__detail__inner__se
.map{|c|c}は不要なので削除しましょう
116行目、127行目、139行目、151行目も同様です

2020-01-22 12:18 UTC, h-hashimoto1212 commented on app/controllers/products_controller.rb
> +    # end
不要なコメントアウトは消しましょう

2020-01-22 12:18 UTC, h-hashimoto1212 commented on app/controllers/products_controller.rb
>    def show
こちらはコメントアウト外しても問題ないはずです

2020-01-22 12:34 UTC, yugo333 commented on app/views/products/edit.html.haml
> +                  = form.select :condition, options_for_select(Product.conditions.map{|c|c} , @product.condition_before_type_cast), {}, {class: "exhibition_main__container__product__detail__inner__se
編集しました

2020-01-23 02:39 UTC, h-hashimoto1212 commented
LGTM

2020-01-23 02:51 UTC, merged